# Loding Libraries

In [1]:
import seaborn as sbs
import matplotlib.pyplot as plt
import numpy as nb
import pandas as pd

# Uploading dataset

In [2]:
df=pd.read_csv('Obesity prediction.csv')

# Introducing with Data

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2111 entries, 0 to 2110
Data columns (total 17 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Gender          2109 non-null   object 
 1   Age             2110 non-null   float64
 2   Height          2110 non-null   float64
 3   Weight          2107 non-null   float64
 4   family_history  2108 non-null   object 
 5   FAVC            2106 non-null   object 
 6   FCVC            2106 non-null   float64
 7   NCP             2109 non-null   float64
 8   CAEC            2106 non-null   object 
 9   SMOKE           2110 non-null   object 
 10  CH2O            2107 non-null   float64
 11  SCC             2111 non-null   object 
 12  FAF             2111 non-null   float64
 13  TUE             2111 non-null   float64
 14  CALC            2108 non-null   object 
 15  MTRANS          2108 non-null   object 
 16  Obesity         2111 non-null   object 
dtypes: float64(8), object(9)
memory u

In [4]:
df.head()

Gender   Age  Height  Weight family_history FAVC  FCVC  NCP       CAEC  \
0  Female  21.0    1.62    64.0            yes   no   2.0  3.0  Sometimes   
1  Female  21.0    1.52    56.0            yes   no   3.0  3.0  Sometimes   
2    Male  23.0    1.80    77.0            yes   no   2.0  3.0  Sometimes   
3    Male  27.0    1.80    87.0             no   no   3.0  3.0  Sometimes   
4    Male  22.0    1.78    89.8             no   no   2.0  1.0  Sometimes   

  SMOKE  CH2O  SCC  FAF  TUE        CALC                 MTRANS  \
0    no   2.0   no  0.0  1.0          no  Public_Transportation   
1   yes   3.0  yes  3.0  0.0   Sometimes  Public_Transportation   
2    no   2.0   no  2.0  1.0  Frequently  Public_Transportation   
3    no   2.0   no  2.0  0.0  Frequently                Walking   
4    no   2.0   no  0.0  0.0   Sometimes  Public_Transportation   

               Obesity  
0        Normal_Weight  
1        Normal_Weight  
2        Normal_Weight  
3   Overweight_Level_I  
4  Overweight_Level_II

# Filling Missing Value

In [5]:
df.isnull().sum()

Gender            2
Age               1
Height            1
Weight            4
family_history    3
FAVC              5
FCVC              5
NCP               2
CAEC              5
SMOKE             1
CH2O              4
SCC               0
FAF               0
TUE               0
CALC              3
MTRANS            3
Obesity           0
dtype: int64

In [6]:
#hanle missing value + function
def toldir(df):
    for col in df.columns:
        if df[col].isnull().any():
            if df[col].dtype=='object':
                df[col].fillna(df[col].mode()[0],inplace=True)
            else:
                df[col].fillna(df[col].mean(),inplace=True)
    return df

In [7]:
toldir(df)

C:\Users\User\AppData\Local\Temp\ipykernel_21376\526236146.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0],inplace=True)
C:\Users\User\AppData\Local\Temp\ipykernel_21376\526236146.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, 

Gender        Age    Height      Weight family_history FAVC  FCVC  NCP  \
0     Female  21.000000  1.620000   64.000000            yes   no   2.0  3.0   
1     Female  21.000000  1.520000   56.000000            yes   no   3.0  3.0   
2       Male  23.000000  1.800000   77.000000            yes   no   2.0  3.0   
3       Male  27.000000  1.800000   87.000000             no   no   3.0  3.0   
4       Male  22.000000  1.780000   89.800000             no   no   2.0  1.0   
...      ...        ...       ...         ...            ...  ...   ...  ...   
2106  Female  20.976842  1.710730  131.408528            yes  yes   3.0  3.0   
2107  Female  21.982942  1.748584  133.742943            yes  yes   3.0  3.0   
2108  Female  22.524036  1.752206  133.689352            yes  yes   3.0  3.0   
2109  Female  24.361936  1.739450  133.346641            yes  yes   3.0  3.0   
2110  Female  23.664709  1.738836  133.472641            yes  yes   3.0  3.0   

           CAEC SMOKE      CH2O  SCC       FAF       TUE        CALC  \
0     Sometimes    no  2.000000   no  0.000000  1.000000          no   
1     Sometimes   yes  3.000000  yes  3.000000  0.000000   Sometimes   
2     Sometimes    no  2.000000   no  2.000000  1.000000  Frequently   
3     Sometimes    no  2.000000   no  2.000000  0.000000  Frequently   
4     Sometimes    no  2.000000   no  0.000000  0.000000   Sometimes   
...         ...   ...       ...  ...       ...       ...         ...   
2106  Sometimes    no  1.728139   no  1.676269  0.906247   Sometimes   
2107  Sometimes    no  2.005130   no  1.341390  0.599270   Sometimes   
2108  Sometimes    no  2.054193   no  1.414209  0.646288   Sometimes   
2109  Sometimes    no  2.852339   no  1.139107  0.586035   Sometimes   
2110  Sometimes    no  2.863513   no  1.026452  0.714137   Sometimes   

                     MTRANS              Obesity  
0     Public_Transportation        Normal_Weight  
1     Public_Transportation        Normal_Weight  
2     Public_Transportation        Normal_Weight  
3                   Walking   Overweight_Level_I  
4     Public_Transportation  Overweight_Level_II  
...                     ...                  ...  
2106  Public_Transportation     Obesity_Type_III  
2107  Public_Transportation     Obesity_Type_III  
2108  Public_Transportation     Obesity_Type_III  
2109  Public_Transportation     Obesity_Type_III  
2110  Public_Transportation     Obesity_Type_III  

[2111 rows x 17 columns]

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2111 entries, 0 to 2110
Data columns (total 17 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Gender          2111 non-null   object 
 1   Age             2111 non-null   float64
 2   Height          2111 non-null   float64
 3   Weight          2111 non-null   float64
 4   family_history  2111 non-null   object 
 5   FAVC            2111 non-null   object 
 6   FCVC            2111 non-null   float64
 7   NCP             2111 non-null   float64
 8   CAEC            2111 non-null   object 
 9   SMOKE           2111 non-null   object 
 10  CH2O            2111 non-null   float64
 11  SCC             2111 non-null   object 
 12  FAF             2111 non-null   float64
 13  TUE             2111 non-null   float64
 14  CALC            2111 non-null   object 
 15  MTRANS          2111 non-null   object 
 16  Obesity         2111 non-null   object 
dtypes: float64(8), object(9)
memory u

# Encoding

In [10]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder

In [11]:
encoder=LabelEncoder()

In [12]:
def raqamla(df):
    for col in df.columns:
        if df[col].dtype=='object':
            if df[col].nunique()<=5:
                dummies=pd.get_dummies(df[col],prefix=col, dtype=int)
                df=pd.concat([df.drop(columns=[col]),dummies],axis=1)
            else:
                df[col]=encoder.fit_transform(df[col])
    return df

In [13]:
df=raqamla(df)

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2111 entries, 0 to 2110
Data columns (total 32 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   Age                           2111 non-null   float64
 1   Height                        2111 non-null   float64
 2   Weight                        2111 non-null   float64
 3   FCVC                          2111 non-null   float64
 4   NCP                           2111 non-null   float64
 5   CH2O                          2111 non-null   float64
 6   FAF                           2111 non-null   float64
 7   TUE                           2111 non-null   float64
 8   Obesity                       2111 non-null   int64  
 9   Gender_Female                 2111 non-null   int64  
 10  Gender_Male                   2111 non-null   int64  
 11  family_history_no             2111 non-null   int64  
 12  family_history_yes            2111 non-null   int64  
 13  FAV

In [15]:
df.head()

Age  Height  Weight  FCVC  NCP  CH2O  FAF  TUE  Obesity  Gender_Female  \
0  21.0    1.62    64.0   2.0  3.0   2.0  0.0  1.0        1              1   
1  21.0    1.52    56.0   3.0  3.0   3.0  3.0  0.0        1              1   
2  23.0    1.80    77.0   2.0  3.0   2.0  2.0  1.0        1              0   
3  27.0    1.80    87.0   3.0  3.0   2.0  2.0  0.0        5              0   
4  22.0    1.78    89.8   2.0  1.0   2.0  0.0  0.0        6              0   

   ...  SCC_yes  CALC_Always  CALC_Frequently  CALC_Sometimes  CALC_no  \
0  ...        0            0                0               0        1   
1  ...        1            0                0               1        0   
2  ...        0            0                1               0        0   
3  ...        0            0                1               0        0   
4  ...        0            0                0               1        0   

   MTRANS_Automobile  MTRANS_Bike  MTRANS_Motorbike  \
0                  0            0                 0   
1                  0            0                 0   
2                  0            0                 0   
3                  0            0                 0   
4                  0            0                 0   

   MTRANS_Public_Transportation  MTRANS_Walking  
0                             1               0  
1                             1               0  
2                             1               0  
3                             0               1  
4                             1               0  

[5 rows x 32 columns]

# Scaling

In [16]:
from sklearn.preprocessing import StandardScaler,MinMaxScaler

In [17]:
scaler=StandardScaler()

In [26]:
def yaxlitla(df):
    num_col=df.select_dtypes(include=['int64','float64']).columns.drop('Obesity')
    df[num_col]=scaler.fit_transform(df[num_col])
    return df

In [27]:
yaxlitla(df)

Age    Height    Weight      FCVC       NCP      CH2O       FAF  \
0    -0.522007 -0.875916 -0.861853 -0.783537  0.404567 -0.011961 -1.188039   
1    -0.522007 -1.948004 -1.168113  1.092463  0.404567  1.621924  2.339750   
2    -0.206766  1.053843 -0.364182 -0.783537  0.404567 -0.011961  1.163820   
3     0.423715  1.053843  0.018643  1.092463  0.404567 -0.011961  1.163820   
4    -0.364387  0.839425  0.125834 -0.783537 -2.166807 -0.011961 -1.188039   
...        ...       ...       ...       ...       ...       ...       ...   
2106 -0.525657  0.096790  1.718709  1.092463  0.404567 -0.456150  0.783135   
2107 -0.367075  0.502618  1.808076  1.092463  0.404567 -0.003579  0.389341   
2108 -0.281788  0.541449  1.806024  1.092463  0.404567  0.076585  0.474971   
2109  0.007902  0.404693  1.792905  1.092463  0.404567  1.380663  0.151471   
2110 -0.101995  0.398111  1.797728  1.092463  0.404567  1.398920  0.018996   

           TUE  Obesity  Gender_Female  ...   SCC_yes  CALC_Always  \
0     0.561997        1       1.013833  ... -0.218272     -0.02177   
1    -1.080625        1       1.013833  ...  4.581439     -0.02177   
2     0.561997        1      -0.986356  ... -0.218272     -0.02177   
3    -1.080625        5      -0.986356  ... -0.218272     -0.02177   
4    -1.080625        6      -0.986356  ... -0.218272     -0.02177   
...        ...      ...            ...  ...       ...          ...   
2106  0.407996        4       1.013833  ... -0.218272     -0.02177   
2107 -0.096251        4       1.013833  ... -0.218272     -0.02177   
2108 -0.019018        4       1.013833  ... -0.218272     -0.02177   
2109 -0.117991        4       1.013833  ... -0.218272     -0.02177   
2110  0.092432        4       1.013833  ... -0.218272     -0.02177   

      CALC_Frequently  CALC_Sometimes   CALC_no  MTRANS_Automobile  \
0           -0.185194       -1.404720  1.517761          -0.524908   
1           -0.185194        0.711885 -0.658865          -0.524908   
2            5.399735       -1.404720 -0.658865          -0.524908   
3            5.399735       -1.404720 -0.658865          -0.524908   
4           -0.185194        0.711885 -0.658865          -0.524908   
...               ...             ...       ...                ...   
2106        -0.185194        0.711885 -0.658865          -0.524908   
2107        -0.185194        0.711885 -0.658865          -0.524908   
2108        -0.185194        0.711885 -0.658865          -0.524908   
2109        -0.185194        0.711885 -0.658865          -0.524908   
2110        -0.185194        0.711885 -0.658865          -0.524908   

      MTRANS_Bike  MTRANS_Motorbike  MTRANS_Public_Transportation  \
0        -0.05768         -0.072375                      0.578991   
1        -0.05768         -0.072375                      0.578991   
2        -0.05768         -0.072375                      0.578991   
3        -0.05768         -0.072375                     -1.727142   
4        -0.05768         -0.072375                      0.578991   
...           ...               ...                           ...   
2106     -0.05768         -0.072375                      0.578991   
2107     -0.05768         -0.072375                      0.578991   
2108     -0.05768         -0.072375                      0.578991   
2109     -0.05768         -0.072375                      0.578991   
2110     -0.05768         -0.072375                      0.578991   

      MTRANS_Walking  
0          -0.165078  
1          -0.165078  
2          -0.165078  
3           6.057758  
4          -0.165078  
...              ...  
2106       -0.165078  
2107       -0.165078  
2108       -0.165078  
2109       -0.165078  
2110       -0.165078  

[2111 rows x 32 columns]

In [28]:
print(df.columns)

Index(['Age', 'Height', 'Weight', 'FCVC', 'NCP', 'CH2O', 'FAF', 'TUE',
       'Obesity', 'Gender_Female', 'Gender_Male', 'family_history_no',
       'family_history_yes', 'FAVC_no', 'FAVC_yes', 'CAEC_Always',
       'CAEC_Frequently', 'CAEC_Sometimes', 'CAEC_no', 'SMOKE_no', 'SMOKE_yes',
       'SCC_no', 'SCC_yes', 'CALC_Always', 'CALC_Frequently', 'CALC_Sometimes',
       'CALC_no', 'MTRANS_Automobile', 'MTRANS_Bike', 'MTRANS_Motorbike',
       'MTRANS_Public_Transportation', 'MTRANS_Walking'],
      dtype='object')


# Model Training Process

In [29]:
from sklearn.model_selection import train_test_split

In [31]:
# Inputlarni x va outputni y bn belgilab ajratib olamiz
x=df.drop('Obesity',axis=1)
y=df['Obesity']

In [41]:
#datasetni tarin va test qismarga taqsimlash
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

# Model Selection

In [33]:
from sklearn.svm import SVC,SVR

In [39]:
svc=SVC(kernel='linear',C=1.0)

In [42]:
svc.fit(x_train,y_train)

SVC(kernel='linear')

In [43]:
y_pred=svc.predict(x_test)

In [44]:
y_pred

array([0, 4, 0, 0, 5, 0, 3, 5, 2, 0, 2, 4, 3, 3, 4, 6, 4, 3, 2, 6, 2, 5,
       4, 2, 1, 6, 6, 4, 4, 0, 4, 5, 6, 1, 0, 4, 2, 1, 1, 1, 1, 3, 1, 1,
       5, 0, 3, 1, 2, 3, 1, 0, 1, 5, 0, 6, 3, 3, 5, 3, 1, 4, 6, 0, 3, 2,
       1, 4, 0, 1, 6, 6, 0, 0, 5, 3, 3, 1, 3, 3, 1, 2, 3, 3, 2, 2, 1, 5,
       1, 6, 5, 3, 0, 5, 2, 0, 5, 2, 1, 3, 2, 2, 4, 2, 6, 2, 1, 4, 4, 3,
       2, 1, 2, 1, 0, 2, 2, 3, 6, 5, 4, 3, 2, 5, 1, 3, 2, 2, 4, 3, 4, 3,
       1, 2, 6, 4, 0, 4, 5, 2, 5, 6, 0, 0, 0, 3, 2, 4, 0, 2, 0, 0, 0, 3,
       2, 5, 6, 5, 0, 0, 1, 0, 2, 0, 3, 0, 3, 5, 5, 6, 1, 6, 3, 4, 2, 6,
       2, 6, 2, 5, 0, 3, 0, 5, 3, 2, 5, 4, 3, 3, 0, 4, 0, 1, 4, 5, 3, 2,
       4, 0, 3, 3, 4, 4, 1, 4, 5, 5, 2, 4, 5, 2, 0, 2, 3, 0, 5, 3, 3, 3,
       4, 6, 3, 5, 3, 6, 0, 4, 5, 5, 5, 4, 1, 5, 1, 2, 2, 2, 2, 0, 6, 6,
       5, 2, 2, 2, 1, 2, 2, 0, 5, 2, 0, 1, 1, 6, 2, 3, 2, 2, 4, 4, 5, 2,
       2, 4, 4, 1, 1, 4, 3, 4, 6, 2, 3, 2, 3, 4, 3, 0, 0, 5, 6, 4, 4, 5,
       2, 6, 0, 3, 2, 5, 1, 2, 0, 6, 3, 3, 6, 6, 1,

# Model Evaluation

In [45]:
from sklearn.metrics import classification_report,accuracy_score

In [48]:
report=classification_report(y_test,y_pred)

In [49]:
print(report)  # wauw 96% accuracy score zor natija

              precision    recall  f1-score   support

           0       0.90      1.00      0.95        56
           1       1.00      0.85      0.92        62
           2       1.00      0.96      0.98        78
           3       0.95      1.00      0.97        58
           4       1.00      0.98      0.99        63
           5       0.92      0.96      0.94        56
           6       0.94      0.96      0.95        50

    accuracy                           0.96       423
   macro avg       0.96      0.96      0.96       423
weighted avg       0.96      0.96      0.96       423



# SVR
# Regresiion

In [51]:
df.head()

Age    Height    Weight      FCVC       NCP      CH2O       FAF  \
0 -0.522007 -0.875916 -0.861853 -0.783537  0.404567 -0.011961 -1.188039   
1 -0.522007 -1.948004 -1.168113  1.092463  0.404567  1.621924  2.339750   
2 -0.206766  1.053843 -0.364182 -0.783537  0.404567 -0.011961  1.163820   
3  0.423715  1.053843  0.018643  1.092463  0.404567 -0.011961  1.163820   
4 -0.364387  0.839425  0.125834 -0.783537 -2.166807 -0.011961 -1.188039   

        TUE  Obesity  Gender_Female  ...   SCC_yes  CALC_Always  \
0  0.561997        1       1.013833  ... -0.218272     -0.02177   
1 -1.080625        1       1.013833  ...  4.581439     -0.02177   
2  0.561997        1      -0.986356  ... -0.218272     -0.02177   
3 -1.080625        5      -0.986356  ... -0.218272     -0.02177   
4 -1.080625        6      -0.986356  ... -0.218272     -0.02177   

   CALC_Frequently  CALC_Sometimes   CALC_no  MTRANS_Automobile  MTRANS_Bike  \
0        -0.185194       -1.404720  1.517761          -0.524908     -0.05768   
1        -0.185194        0.711885 -0.658865          -0.524908     -0.05768   
2         5.399735       -1.404720 -0.658865          -0.524908     -0.05768   
3         5.399735       -1.404720 -0.658865          -0.524908     -0.05768   
4        -0.185194        0.711885 -0.658865          -0.524908     -0.05768   

   MTRANS_Motorbike  MTRANS_Public_Transportation  MTRANS_Walking  
0         -0.072375                      0.578991       -0.165078  
1         -0.072375                      0.578991       -0.165078  
2         -0.072375                      0.578991       -0.165078  
3         -0.072375                     -1.727142        6.057758  
4         -0.072375                      0.578991       -0.165078  

[5 rows x 32 columns]

In [59]:
svr=SVR(kernel='linear',C=0.5)

In [64]:
svr.fit(x_train,y_train)

SVR(C=0.5, kernel='linear')

In [65]:
y_pred=svr.predict(x_test)

In [54]:
y_pred

array([-5.87976168e-02,  3.99704058e+00,  6.93412829e-01,  4.07966677e-01,
        1.92677358e+00,  9.97860184e-01,  3.19676017e+00,  2.71345307e+00,
        2.49103697e+00,  3.13652508e-01,  2.30677080e+00,  3.81150418e+00,
        2.77625526e+00,  3.12803686e+00,  3.88043023e+00,  2.17142133e+00,
        4.04793013e+00,  3.00301935e+00,  2.91246685e+00,  1.72128355e+00,
        2.47717430e+00,  2.22454184e+00,  3.81175774e+00,  2.25520162e+00,
        7.37051223e-01,  2.79948438e+00,  1.68936263e+00,  4.15088536e+00,
        3.86750665e+00,  7.13008057e-01,  3.89973139e+00,  2.75432842e+00,
        4.98636152e+00,  1.96045232e+00,  6.30650552e-01,  3.77028076e+00,
        2.28190342e+00,  6.42677090e-01,  1.28387958e+00,  2.20403523e-01,
        1.42653138e+00,  3.02685466e+00,  1.13001156e+00,  3.74965016e-01,
        1.83472004e+00,  2.82734384e-01,  3.06354886e+00,  2.33275963e+00,
        2.67314056e+00,  3.02723135e+00,  3.90575119e+00,  9.71396790e-01,
        9.36875469e-01,  

In [66]:
# model evaluation
from sklearn.metrics import r2_score,mean_absolute_error

In [67]:
r2=r2_score(y_test,y_pred)
mae=mean_absolute_error(y_test,y_pred)

In [ ]:
print(r2)  # yaxshimas error juda kop r2 esa atigi 8% while mae 118%   c=0.5 qiilsa ham deyarlik bir xil natija oldik afsus 
print(mae)

0.08540904409277095
1.1812419957049314


# Linear Regression

In [70]:
from sklearn.linear_model import LinearRegression

In [72]:
lr=LinearRegression()

In [73]:
lr.fit(x_train,y_train)

LinearRegression()

In [74]:
y_pred=lr.predict(x_test)

In [75]:
y_pred

array([ 0.6809393 ,  4.09798437,  1.81099692,  0.77791341,  4.0711453 ,
        2.37279391,  4.00219808,  3.49994452,  3.53320432,  1.32431603,
        3.32519641,  3.80987142,  3.46649398,  3.84889528,  3.91856574,
        2.23644572,  3.76424002,  3.77827879,  3.56899091,  3.10948162,
        3.66321839,  3.24736017,  3.93416767,  3.21991816,  1.85717668,
        3.47632098,  2.82341426,  3.93276883,  4.00285223,  2.06287467,
        4.05458169,  3.93116998,  4.15798662,  3.04678674,  1.2783002 ,
        3.91109781,  3.22646509,  0.74404742,  1.41196009,  0.55088493,
        2.08309153,  3.84765174,  2.78920662,  1.90857652,  2.9688991 ,
        0.80412667,  3.87883146,  3.83703021,  3.18618185,  3.65156895,
        2.63999962,  2.04661834,  1.84480794,  3.99579666,  1.19008248,
        4.24761277,  4.37900289,  3.67028431,  2.2030444 ,  3.61428748,
       -0.13024399,  4.1393708 ,  3.70058919,  1.42604579,  3.70515232,
        3.16261355,  1.4018134 ,  4.46299465,  1.48378908,  1.37

In [76]:
from sklearn.metrics import r2_score,mean_absolute_error

In [77]:
r2=r2_score(y_test,y_pred)
mae=mean_absolute_error(y_test,y_pred)

In [78]:
print(r2)
print(mae)

0.2597672163883067
1.3706345023577087


# Logistic Regression

In [80]:
from sklearn.linear_model import LogisticRegression

In [81]:
lg=LogisticRegression()

In [82]:
lg.fit(x_train,y_train)

LogisticRegression()

In [83]:
y_pred=lg.predict(x_test)

In [84]:
y_pred

array([0, 4, 0, 0, 5, 0, 3, 5, 2, 0, 2, 4, 3, 3, 4, 2, 4, 3, 3, 6, 2, 5,
       4, 2, 1, 6, 6, 4, 4, 0, 4, 6, 2, 1, 0, 4, 2, 1, 0, 1, 0, 3, 1, 1,
       5, 0, 3, 5, 2, 3, 1, 0, 1, 5, 0, 6, 3, 3, 5, 3, 1, 4, 6, 0, 3, 2,
       1, 4, 0, 1, 6, 2, 0, 0, 6, 3, 3, 5, 3, 3, 1, 2, 3, 3, 2, 2, 1, 5,
       1, 6, 6, 3, 0, 1, 2, 0, 5, 2, 1, 3, 3, 2, 4, 2, 6, 2, 1, 4, 4, 3,
       2, 1, 2, 1, 0, 2, 2, 3, 6, 5, 4, 3, 2, 5, 6, 3, 2, 2, 4, 3, 4, 3,
       1, 2, 6, 4, 0, 4, 1, 2, 6, 5, 0, 0, 0, 3, 2, 4, 0, 2, 0, 0, 0, 3,
       2, 6, 6, 6, 0, 0, 5, 0, 2, 0, 3, 0, 3, 5, 5, 6, 5, 6, 3, 4, 2, 6,
       2, 6, 2, 1, 0, 3, 0, 5, 3, 2, 5, 4, 3, 3, 0, 4, 0, 1, 4, 1, 3, 4,
       4, 0, 3, 3, 4, 4, 1, 4, 5, 5, 6, 4, 5, 2, 0, 2, 3, 0, 5, 2, 3, 2,
       4, 6, 3, 1, 3, 6, 0, 4, 5, 6, 5, 4, 1, 5, 1, 2, 2, 2, 2, 0, 6, 6,
       5, 2, 6, 3, 1, 2, 2, 0, 5, 2, 0, 6, 1, 6, 2, 3, 2, 2, 4, 4, 5, 2,
       2, 4, 4, 1, 5, 4, 3, 4, 6, 2, 3, 2, 3, 4, 3, 0, 0, 5, 6, 4, 4, 5,
       2, 6, 0, 3, 2, 5, 5, 2, 0, 6, 3, 3, 6, 6, 1,

In [85]:
from sklearn.metrics import classification_report, accuracy_score

In [86]:
report=classification_report(y_test,y_pred)


In [ ]:
print(report)   # ijobiy natija accuracy score imiz 87%

              precision    recall  f1-score   support

           0       0.88      1.00      0.93        56
           1       0.89      0.65      0.75        62
           2       0.93      0.87      0.90        78
           3       0.89      0.97      0.93        58
           4       0.98      0.98      0.98        63
           5       0.73      0.73      0.73        56
           6       0.73      0.86      0.79        50

    accuracy                           0.87       423
   macro avg       0.86      0.87      0.86       423
weighted avg       0.87      0.87      0.86       423



# Decision Tree

In [88]:
from sklearn.tree import DecisionTreeClassifier

In [89]:
dt=DecisionTreeClassifier()

In [90]:
dt.fit(x_train,y_train)

DecisionTreeClassifier()

In [91]:
y_pred=dt.predict(x_test)

In [92]:
y_pred

array([0, 4, 0, 0, 1, 0, 3, 5, 2, 0, 2, 4, 2, 3, 4, 6, 4, 3, 2, 6, 2, 5,
       4, 2, 1, 6, 6, 4, 4, 0, 4, 5, 6, 1, 0, 4, 2, 1, 1, 1, 1, 3, 1, 1,
       5, 0, 3, 1, 2, 3, 1, 1, 1, 5, 0, 6, 3, 3, 5, 3, 1, 4, 6, 0, 2, 2,
       1, 4, 0, 0, 6, 6, 0, 0, 5, 3, 3, 5, 3, 3, 1, 2, 3, 3, 2, 2, 1, 6,
       1, 6, 5, 3, 0, 5, 2, 0, 5, 2, 1, 3, 2, 2, 4, 2, 6, 2, 1, 4, 4, 3,
       2, 1, 2, 1, 0, 2, 2, 3, 6, 1, 4, 3, 2, 6, 1, 3, 2, 2, 4, 3, 4, 3,
       1, 2, 6, 4, 0, 4, 5, 2, 5, 6, 0, 0, 1, 3, 2, 4, 0, 2, 0, 0, 1, 3,
       2, 5, 6, 5, 0, 0, 5, 1, 2, 0, 3, 0, 3, 1, 5, 6, 1, 6, 3, 4, 2, 6,
       2, 5, 2, 1, 1, 3, 0, 5, 3, 2, 5, 4, 3, 3, 0, 4, 0, 1, 4, 1, 3, 2,
       4, 0, 3, 3, 4, 4, 1, 4, 5, 5, 2, 4, 5, 2, 0, 2, 3, 0, 5, 3, 3, 2,
       4, 6, 3, 5, 3, 6, 0, 4, 5, 5, 5, 4, 1, 5, 1, 2, 2, 2, 2, 0, 6, 6,
       5, 2, 6, 2, 1, 2, 4, 0, 5, 2, 0, 1, 1, 6, 2, 3, 2, 2, 4, 4, 5, 2,
       2, 4, 4, 1, 1, 4, 3, 4, 5, 2, 3, 2, 3, 4, 3, 0, 0, 5, 6, 4, 4, 5,
       2, 6, 0, 3, 2, 5, 0, 2, 0, 5, 3, 3, 6, 6, 1,

In [93]:
report=classification_report(y_test,y_pred)


In [ ]:
print(report) # 94 % accuracy score juda ajoyib natija

              precision    recall  f1-score   support

           0       0.90      0.98      0.94        56
           1       0.90      0.87      0.89        62
           2       0.96      0.95      0.95        78
           3       0.95      0.95      0.95        58
           4       0.98      0.98      0.98        63
           5       0.93      0.91      0.92        56
           6       0.98      0.96      0.97        50

    accuracy                           0.94       423
   macro avg       0.94      0.94      0.94       423
weighted avg       0.94      0.94      0.94       423



# Random Forest

In [97]:
from sklearn.ensemble import RandomForestClassifier

In [98]:
rf=RandomForestClassifier()

In [99]:
rf.fit(x_train,y_train)

RandomForestClassifier()

In [100]:
y_pred=rf.predict(x_test)

In [101]:
y_pred

array([0, 4, 0, 0, 1, 0, 3, 5, 2, 0, 2, 4, 3, 3, 4, 6, 4, 3, 2, 6, 2, 5,
       4, 2, 1, 6, 6, 4, 4, 0, 4, 5, 6, 1, 0, 4, 2, 1, 1, 1, 1, 3, 1, 1,
       5, 0, 3, 1, 2, 3, 1, 1, 1, 5, 0, 5, 3, 3, 5, 3, 1, 4, 6, 0, 3, 2,
       1, 4, 0, 1, 6, 6, 0, 0, 5, 3, 3, 5, 3, 3, 1, 2, 3, 3, 2, 2, 1, 6,
       1, 6, 6, 3, 0, 1, 6, 0, 1, 2, 5, 3, 2, 2, 4, 2, 6, 2, 1, 4, 4, 3,
       2, 1, 6, 1, 0, 2, 2, 3, 6, 1, 4, 3, 2, 5, 1, 3, 2, 2, 4, 3, 4, 3,
       1, 2, 6, 4, 0, 4, 1, 2, 5, 6, 0, 0, 1, 3, 2, 4, 0, 2, 0, 0, 1, 3,
       2, 5, 6, 5, 0, 0, 1, 1, 2, 0, 3, 0, 2, 1, 5, 6, 1, 6, 3, 4, 2, 6,
       2, 6, 2, 1, 0, 3, 0, 5, 3, 2, 5, 4, 3, 3, 0, 4, 0, 1, 4, 1, 3, 2,
       4, 0, 3, 3, 4, 4, 1, 4, 5, 5, 2, 4, 5, 2, 0, 2, 3, 0, 5, 3, 3, 2,
       4, 6, 3, 5, 3, 6, 0, 4, 5, 5, 5, 4, 1, 5, 1, 2, 2, 2, 2, 0, 6, 6,
       5, 2, 5, 2, 1, 2, 2, 0, 5, 2, 0, 5, 1, 6, 2, 3, 2, 2, 4, 4, 5, 2,
       2, 4, 4, 1, 1, 4, 3, 4, 6, 2, 3, 2, 3, 4, 3, 0, 0, 5, 6, 4, 4, 5,
       2, 6, 0, 3, 2, 5, 1, 2, 0, 5, 3, 3, 6, 6, 1,

In [102]:
report=classification_report(y_test,y_pred)

In [103]:
print(report)

              precision    recall  f1-score   support

           0       0.96      0.96      0.96        56
           1       0.86      0.90      0.88        62
           2       0.99      0.95      0.97        78
           3       0.97      0.98      0.97        58
           4       1.00      0.98      0.99        63
           5       0.87      0.86      0.86        56
           6       0.94      0.96      0.95        50

    accuracy                           0.94       423
   macro avg       0.94      0.94      0.94       423
weighted avg       0.94      0.94      0.94       423



# Comparing Models

In [104]:
from tabulate import tabulate

In [117]:
results=[
    ['Super Vector Classifier',0.96],
    ['Super Vector Regressor',0.08],
    ['Linear Regression',0.25],
    ['Logistic Regression',0.87],
    ['Decision Tree Classifier',0.94],
    ['Random Forest Classifier',0.94]
]

In [118]:
headers=('Algoritm','Accuracy_Score')

In [119]:
table=tabulate(results,headers=headers,tablefmt='grid')

In [ ]:
print(table)   # Demak eng zor natija Super Vector Classifier algoritmida kuzatdik chunki dataset clasificationda

+--------------------------+------------------+
| Algoritm                 |   Accuracy_Score |
+==========================+==================+
| Super Vector Classifier  |             0.96 |
+--------------------------+------------------+
| Super Vector Regressor   |             0.08 |
+--------------------------+------------------+
| Linear Regression        |             0.25 |
+--------------------------+------------------+
| Logistic Regression      |             0.87 |
+--------------------------+------------------+
| Decision Tree Classifier |             0.94 |
+--------------------------+------------------+
| Random Forest Classifier |             0.94 |
+--------------------------+------------------+


# Modelni saqlash
# Joblib

In [121]:
import joblib

In [122]:
from joblib import dump,load

In [123]:
dump(svc,'Obesity_prediction.joblib')

['Obesity_prediction.joblib']

In [124]:
model=load('Obesity_prediction.joblib')

In [125]:
model

SVC(kernel='linear')