# Loding Libraries

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sbs

# Uploading dataset

In [4]:
df=pd.read_csv('college_student_placement_dataset.csv')

# Introducing with Data

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   College_ID              10000 non-null  object 
 1   IQ                      10000 non-null  int64  
 2   Prev_Sem_Result         10000 non-null  float64
 3   CGPA                    10000 non-null  float64
 4   Academic_Performance    10000 non-null  int64  
 5   Internship_Experience   10000 non-null  object 
 6   Extra_Curricular_Score  10000 non-null  int64  
 7   Communication_Skills    10000 non-null  int64  
 8   Projects_Completed      10000 non-null  int64  
 9   Placement               10000 non-null  object 
dtypes: float64(2), int64(5), object(3)
memory usage: 781.4+ KB


In [6]:
df.head()

College_ID   IQ  Prev_Sem_Result  CGPA  Academic_Performance  \
0    CLG0030  107             6.61  6.28                     8   
1    CLG0061   97             5.52  5.37                     8   
2    CLG0036  109             5.36  5.83                     9   
3    CLG0055  122             5.47  5.75                     6   
4    CLG0004   96             7.91  7.69                     7   

  Internship_Experience  Extra_Curricular_Score  Communication_Skills  \
0                    No                       8                     8   
1                    No                       7                     8   
2                    No                       3                     1   
3                   Yes                       1                     6   
4                    No                       8                    10   

   Projects_Completed Placement  
0                   4        No  
1                   0        No  
2                   1        No  
3                   1        No  
4                   2        No

# Encoding

In [8]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder

In [34]:
encoder=LabelEncoder()


In [14]:
cardinality=df.nunique()

In [15]:
cardinality            #onehotencoder dan foydalanish faqat 3 ta column un qolgani LabelEncoder

College_ID                100
IQ                        104
Prev_Sem_Result           501
CGPA                      590
Academic_Performance       10
Internship_Experience       2
Extra_Curricular_Score     11
Communication_Skills       10
Projects_Completed          6
Placement                   2
dtype: int64

In [36]:
def raqamla(df):
    for col in df.columns:
        if df[col].dtype=='object':
            if df[col].nunique()<=5:
                dummies=pd.get_dummies(df[col],prefix=col, dtype=int)
                df=pd.concat([df.drop(columns=[col]),dummies],axis=1)
            else:
                df[col]=encoder.fit_transform(df[col])
    return df   

In [37]:
df=raqamla(df)

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   College_ID                 10000 non-null  int64  
 1   IQ                         10000 non-null  int64  
 2   Prev_Sem_Result            10000 non-null  float64
 3   CGPA                       10000 non-null  float64
 4   Academic_Performance       10000 non-null  int64  
 5   Extra_Curricular_Score     10000 non-null  int64  
 6   Communication_Skills       10000 non-null  int64  
 7   Projects_Completed         10000 non-null  int64  
 8   Internship_Experience_No   10000 non-null  int64  
 9   Internship_Experience_Yes  10000 non-null  int64  
 10  Placement_No               10000 non-null  int64  
 11  Placement_Yes              10000 non-null  int64  
dtypes: float64(2), int64(10)
memory usage: 937.6 KB


# Scaling

In [38]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()

In [47]:
num_col=df.select_dtypes(include=['int64','float64']).columns.drop('Placement_Yes')

In [48]:
num_col

Index(['College_ID', 'IQ', 'Prev_Sem_Result', 'CGPA', 'Academic_Performance',
       'Extra_Curricular_Score', 'Communication_Skills', 'Projects_Completed',
       'Internship_Experience_No', 'Internship_Experience_Yes',
       'Placement_No'],
      dtype='object')

In [52]:
def taqribla(df):
    df[num_col]=scaler.fit_transform(df[num_col])
    return df


In [53]:
taqribla (df)

College_ID        IQ  Prev_Sem_Result      CGPA  Academic_Performance  \
0       0.292929  0.564103            0.322  0.293919              0.777778   
1       0.606061  0.478632            0.104  0.140203              0.777778   
2       0.353535  0.581197            0.072  0.217905              0.888889   
3       0.545455  0.692308            0.094  0.204392              0.555556   
4       0.030303  0.470085            0.582  0.532095              0.666667   
...          ...       ...              ...       ...                   ...   
9995    0.202020  0.666667            0.682  0.633446              0.333333   
9996    0.979798  0.247863            0.850  0.810811              0.666667   
9997    0.656566  0.410256            0.216  0.288851              0.222222   
9998    0.444444  0.564103            0.754  0.739865              0.222222   
9999    0.595960  0.581197            0.882  0.883446              0.777778   

      Extra_Curricular_Score  Communication_Skills  Projects_Completed  \
0                        0.8              0.777778                 0.8   
1                        0.7              0.777778                 0.0   
2                        0.3              0.000000                 0.2   
3                        0.1              0.555556                 0.2   
4                        0.8              1.000000                 0.4   
...                      ...                   ...                 ...   
9995                     0.1              0.777778                 0.0   
9996                     0.0              0.666667                 0.4   
9997                     0.3              0.888889                 1.0   
9998                     0.7              0.444444                 0.2   
9999                     0.3              0.444444                 1.0   

      Internship_Experience_No  Internship_Experience_Yes  Placement_No  \
0                          1.0                        0.0           1.0   
1                          1.0                        0.0           1.0   
2                          1.0                        0.0           1.0   
3                          0.0                        1.0           1.0   
4                          1.0                        0.0           1.0   
...                        ...                        ...           ...   
9995                       1.0                        0.0           0.0   
9996                       1.0                        0.0           1.0   
9997                       0.0                        1.0           1.0   
9998                       1.0                        0.0           1.0   
9999                       1.0                        0.0           1.0   

      Placement_Yes  
0                 0  
1                 0  
2                 0  
3                 0  
4                 0  
...             ...  
9995              1  
9996              0  
9997              0  
9998              0  
9999              0  

[10000 rows x 12 columns]

# Model Training Process

In [81]:
# Inputlarni x va outputni y bn belgilab ajratib olamiz
x=df.drop('Placement_Yes',axis=1)
y=df['Placement_Yes']

In [82]:
from sklearn.model_selection import train_test_split

In [88]:
# datalarni qismlarga ajratish
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

# Model Selection

In [84]:
from sklearn.ensemble import RandomForestClassifier             

In [85]:
rf=RandomForestClassifier()

In [86]:
rf

RandomForestClassifier()

In [89]:
rf.fit(x_train,y_train)

RandomForestClassifier()

In [93]:
y_pred=rf.predict(x_test)

In [94]:
y_pred

array([0, 0, 0, ..., 0, 0, 0], shape=(2000,))

In [95]:
x_test

College_ID        IQ  Prev_Sem_Result      CGPA  Academic_Performance  \
6252    0.282828  0.837607            0.458  0.456081              0.777778   
4684    0.696970  0.367521            0.656  0.667230              0.777778   
1731    0.070707  0.452991            0.052  0.189189              0.777778   
4742    0.969697  0.504274            0.244  0.295608              0.555556   
4521    0.181818  0.641026            0.198  0.312500              0.555556   
...          ...       ...              ...       ...                   ...   
6412    0.818182  0.264957            0.506  0.483108              0.222222   
8285    0.090909  0.623932            0.630  0.576014              0.777778   
7853    0.919192  0.572650            0.770  0.721284              0.222222   
1095    0.252525  0.487179            0.978  0.859797              0.000000   
6929    0.101010  0.358974            0.430  0.380068              1.000000   

      Extra_Curricular_Score  Communication_Skills  Projects_Completed  \
6252                     0.8              0.333333                 0.8   
4684                     0.3              0.222222                 1.0   
1731                     0.7              1.000000                 0.8   
4742                     0.8              0.555556                 0.6   
4521                     0.2              0.888889                 1.0   
...                      ...                   ...                 ...   
6412                     0.6              0.777778                 0.6   
8285                     0.6              0.222222                 0.4   
7853                     0.6              0.888889                 0.2   
1095                     0.3              0.000000                 0.0   
6929                     0.4              0.777778                 0.0   

      Internship_Experience_No  Internship_Experience_Yes  Placement_No  
6252                       1.0                        0.0           1.0  
4684                       0.0                        1.0           1.0  
1731                       1.0                        0.0           1.0  
4742                       0.0                        1.0           1.0  
4521                       1.0                        0.0           0.0  
...                        ...                        ...           ...  
6412                       1.0                        0.0           1.0  
8285                       0.0                        1.0           1.0  
7853                       0.0                        1.0           1.0  
1095                       1.0                        0.0           1.0  
6929                       0.0                        1.0           1.0  

[2000 rows x 11 columns]

# Model Evaluation

In [98]:
from sklearn.metrics import classification_report,accuracy_score

In [99]:
report=classification_report(y_test,y_pred)
score=accuracy_score(y_test,y_pred)

In [100]:
print(report)
print(score)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1674
           1       1.00      1.00      1.00       326

    accuracy                           1.00      2000
   macro avg       1.00      1.00      1.00      2000
weighted avg       1.00      1.00      1.00      2000

1.0


# Decision Tree Classifier

In [ ]:
from sklearn.tree import DecisionTreeClassifier


In [ ]:
dt=DecisionTreeClassifier()


In [106]:
dt.fit(x_train,y_train)

DecisionTreeClassifier()

In [107]:
y_pred=dt.predict(x_test)

In [108]:
y_pred

array([0, 0, 0, ..., 0, 0, 0], shape=(2000,))

In [110]:
report=classification_report(y_test,y_pred)
score=accuracy_score(y_test,y_pred)

In [111]:
print(report)
print(score)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1674
           1       1.00      1.00      1.00       326

    accuracy                           1.00      2000
   macro avg       1.00      1.00      1.00      2000
weighted avg       1.00      1.00      1.00      2000

1.0


# Logistic Regression

In [112]:
from sklearn.linear_model import LogisticRegression

In [113]:
lg=LogisticRegression()

In [114]:
lg.fit(x_train,y_train)

LogisticRegression()

In [115]:
y_pred=lg.predict(x_test)

In [116]:
y_pred

array([0, 0, 0, ..., 0, 0, 0], shape=(2000,))

In [117]:
report=classification_report(y_test,y_pred)
score=accuracy_score(y_test,y_pred)

In [118]:
print(report)
print(score)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1674
           1       1.00      1.00      1.00       326

    accuracy                           1.00      2000
   macro avg       1.00      1.00      1.00      2000
weighted avg       1.00      1.00      1.00      2000

1.0


# Compare with tabulate

In [120]:
from tabulate import tabulate

In [135]:
results=[
    ['Random Forest',1.0],
    ['Decision Tree',1.0],
    ['Logostic Regresiion',1.0]
]

In [136]:
headers=['Algoritms','Accuracy_score']

In [138]:
table=tabulate(results,headers=headers,tablefmt='grid')


In [139]:
print(table)

+---------------------+------------------+
| Algoritms           |   Accuracy_score |
+=====================+==================+
| Random Forest       |                1 |
+---------------------+------------------+
| Decision Tree       |                1 |
+---------------------+------------------+
| Logostic Regresiion |                1 |
+---------------------+------------------+
